[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
    "cd job_board_aggregator-main/job_board_aggregator-main",
    "pip install -r requirements.txt"
]

[start]
cmd = "cd job_board_aggregator-main/job_board_aggregator-main && python run_server.py"
